### ISSUE TITLE
Fails to build from source

### ISSUE THREAD

**Issue by kloetzl** [refresh-bio/kmer-db#1]
In `libs/` there seem to be a bunch of binary files which won't link on my computers. Can you provide an alternative? Dynamically linking with preinstalled packages seems to work.

**Comment by agudys** [comment]
Hello! We'll provide a possibility to link libraries dynamically ASAP.

**Comment by sam217pa** [comment]
+1 !
Been trying to compile on mac osx but the `libs/*.a` were compiled for linux so the linker can't do a proper job.

(Thanks and congrats for the bioinformatics paper !)

**Comment by agudys** [comment]
Hello Fabian and Sam,
I updated the makefile so now by default it links Kmer-db against system-installed zlib. In order to change this, INTERNAL_ZLIB variable at the beginning of makefile has to be set to true. Please let me know if it helps.
Adam

(Thank you for congrats :))

**Comment by sam217pa** [comment]
Thank you for the quick fix, it compiles just fine on my machine now !

**Comment by kloetzl** [comment]
The build still fails, because my machine doesn't support avx2.

**Comment by agudys** [comment]
Indeed, while the binary should work on all platforms (it detectes whether AVX2 is present and executes proper code), the build may fail on CPUs without AVX2. I'll fix this soon and let you know.

**Comment by agudys** [comment]
Dear Fabian,
I added a switch NO_AVX2 at the top of the makefile which prevents from AVX2 compilation. Note, that AVX2-compatible binary should also work on non-AVX machine as supported extensions are determined at runtime.  Please try and let me know.

**Comment by kloetzl** [comment]
Now it compiles, but doesn't run on computers without AVX. I guess, that is ok, if you mention that as a requirement.

**Comment by agudys** [comment]
I've added the information in README about AVX as an obligatory requirement for Kmer-db, and AVX2 as optional ferature. Thanks!
