### ISSUE TITLE
Distance description

### ISSUE THREAD

**Issue by royfrancis** [refresh-bio/kmer-db#5]
Is there a description somewhere for the contents of the distance output file? Is it a tabular format? What are rows/columns?

My aim is to get to this:

```
A       B       dist
sample1 sample2 0.2
sample1 sample3 0.6
...
```

**Comment by agudys** [comment]
Hello,
Files produced by the `distance` mode are in the following form:
* in the first row there are names of *N* analyzed samples,
* then there is a lower-triangular *N*-by-*N* distance/similarity matrix.
