### ISSUE TITLE
Use full paths as sample names in the database

### ISSUE THREAD

**Issue by agudys** [refresh-bio/kmer-db#7]
Currently, only a filename (without a full path) is used internally in the database as a sample name. This may be a problem when samples differ by paths, not the filenames.

**Comment by rmostowy** [comment]
It's actually more than this – when the filename is compressed, for example GCF_000505285.1.fa.gz, one has to remove only the last compression (i.e., provide GCF_000505285.1.fa). Sounds like it would be easy to change this?

**Comment by agudys** [comment]
When loading genome files, exact filenames are examined first. If this fails, an attempt to add predefined extensions is made.
