### ISSUE TITLE
Please add a license and the appropriate LICENSE or COPYING file

### ISSUE THREAD

**Issue by andersgs** [refresh-bio/kmer-db#8]
I am hoping to add kmer-db to bioconda. But, a license file is required.

**Comment by agudys** [comment]
Hello, 
The LICENSE file has been added. Thanks a lot for your effort! We were thinking about bioconda but somehow never managed to do this.

Regards,
Adam

**Comment by andersgs** [comment]
Right back at you. I’ll work on it this week. Should be fairly easy.
